name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Thiết lập SSH để kết nối tới server
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Thêm server vào known_hosts
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 89.117.36.180 >> ~/.ssh/known_hosts

      # 4. Debug SSH để kiểm tra kết nối
      - name: Debug SSH
        run: ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@89.117.36.180 "echo 'SSH connection successful'"

      # 5. Deploy code lên server
      - name: Deploy to Server
        run: |
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@89.117.36.180 << 'EOF'
            cd /root/okr-admin
            git pull origin main
            npm install
            npm run build
            pm2 restart 4
          EOF
